apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkinsserviceaccount-role-binding
  namespace: testing
subjects:
- kind: ServiceAccount
  name: jenkins-service-account
  namespace: testing
roleRef:
  kind: Role
  name: jenkinsserviceaccount-role
  apiGroup: rbac.authorization.k8s.io
