apiVersion: v1
kind: ConfigMap
metadata:
  name: encryption-provider-config
  namespace: kube-system
data:
  config.yaml: |
    kind: EncryptionConfiguration
    apiVersion: v1
    resources:
      - resources:
          - secrets
        providers:
          - kms:
              name: eks-secrets
              key:
                arn: arn:aws:kms:us-east-1:010438494949:key/b30c854f-8f53-42b6-88a6-3d64bfff7821
          - identity: {}
