apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-imageupdaterservice-account
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::010438494949:role/Argocd-imageupdater-role
